### ISSUE TITLE
Adding headers support from cli 

### ISSUE THREAD

**Issue by arbazkiraak** [s0md3v/XSStrike#128]
Hello @s0md3v,

* cli arguments play a very important role in cli tools ,Many tools such as `SQLMAP` `Commix` `TPLMAP` supports parsing headers through cli by adding it over `\n` and parsing over dict later. XSStrike already have an option `--headers` to parse the raw HTTP requests by prompting & parsing those HTTP requests into dictionary `https://github.com/s0md3v/XSStrike/blob/master/core/utils.py`  and adding over requests module along with url and payloads.

I have made some changes to do parse through cli.

```
parser.add_argument('-H','--headers', help='add headers')
```
```
if args.headers:
	headers_cli = args.headers
	headers = dict(head.split(':') for head in headers_cli.split(r'^\n'))
else:
	from core.config import headers
```
```
#add_headers = args.add_headers
add_headers = headers
```

Trying Authentication Based XSS on DVWA:

```
→ python3 xsstrike.py -H "User-Agent:Mozilla/5.0^\nCookie:PHPSESSID=2341gh7po82t6d3oc92v0bifc5;security=low" -u "http://site.com/vulnerabilities/xss_r/?name=xxxxxx"

        XSStrike v3.0.4

[~] Checking for DOM vulnerabilities
[+] WAF Status: Offline
[!] Testing parameter: name
[!] Reflections found: 1
[~] Analysing reflections
[~] Generating payloads
[!] Payloads generated: 3072
------------------------------------------------------------
[+] Payload: <A%0aoNmoUsEOver+=+confirm() x>z
[!] Efficiency: 100
[!] Confidence: 10
[?] Would you like to continue scanning? [y/N]```

**Comment by s0md3v** [comment]
Hi @arbazkiraak ,

First of all, there's no "standard" for how headers should be supplied to the program.
I added this prompt thing because the standard way of supplying headers (e.g. in sqlmap or commix) is not convenient.

I understand your concern but I don't think it's wise to replace XSStrike's core functionality with something else that you think is better or is the "standard".

Thanks for raising this issue with the incredible level of details, that would have helped.
I am closing this issue for now.
However, we can have another option for headers from CLI if other people want it too because I have asked some people I know to review the tool and they pointed out that this prompt feature is great.

Thanks.
Let me know if you have any other suggestions.
