### ISSUE TITLE
--data doesnt take alle parameters

### ISSUE THREAD

**Issue by gboisec** [s0md3v/XSStrike#143]
Using --data with following parameters "categories=353232&regions=288800&countries=1234&chk_not_mandatory=0&country_selected=18743&chk_mandatory=1&chk_conditional=1". XSStrike just takes the first Parameter and does the following (intercepted with proxy) = "categories=v3dm0s&xss=%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E" 

All the other Parameters which are neccessary for the request are ignored.

**Environment:**
 - OS: [e.g. Kali Rolling 2018.4]
 - Browser [e.g. Firefox 60.2]
 - Python version [e.g. 3.7]

**Some Questions**

- [x ] I am using the latest version of XSStrike.
- [ x] I installed the dependecies using `pip3` instead of `pip`
- [ x] I have read the documentation before submitting this issue.
- [x ] I have checked the other issues to see if someone reported this before.

**Comment by s0md3v** [comment]
`<script>` tags are easily detected by security mechanisms, XSStrike doesn't use them while generating payloads (unless in JS context).
But since they are easily detected, they are perfect for detecting WAFs and that's why XSStrike does this:
`xss=<script>alert("XSS")</script>`

**But why it doesn't use all the parameters?**
It does. But while detecting WAF, it removes other parameters because some WAFs can detect that and that's what we want.
