### ISSUE TITLE
Event Handler Context

### ISSUE THREAD

**Issue by TimurNurlygayanov** [s0md3v/XSStrike#148]
**Problem:**
We have a simple game for XSS injections, but XSStrike can't find XSS issues in this simple example.

**How To Reproduce:**
1) Run: python3 xsstrike.py -u "https://xss-game.appspot.com/level1"
2) Run: python3 xsstrike.py -u "https://xss-game.appspot.com/level1/frame"

**Expected Result:**
XSStrike will find the vulnerability (because it is here and it is very easy to find).

**Actual Result:**
 Checking for DOM vulnerabilities
 No parameters to test.

**Comment by TimurNurlygayanov** [comment]
and it will be cool if XSStrike will find all vulnerabilities in this game :)

**Comment by TimurNurlygayanov** [comment]
so and even when it found real reflection, it can't suggest any vector:

```
python3 xsstrike.py -u "https://xss-game.appspot.com/level4/frame?timer=4"

	XSStrike v3.0.5

 Checking for DOM vulnerabilities
 WAF Status: Offline
 Testing parameter: timer
 Reflections found: 2
 Analysing reflections
 Generating payloads
 No vectors were crafted
```

**Comment by s0md3v** [comment]
XSStrike now supports event handler context as well but you still will not be able to win this game because such challenges involve a lot of tricks to be used to succeed.

For example, the payload generated for this challenge by XSStrike is:
`');alert()//`
But the challenge can only be completed with:
`')%3Balert()//`

`%3B` is the URL encoded form of `;` 

Using  a tool for such complication scenarios is not recommended.
