### ISSUE TITLE
Many false positives ?

### ISSUE THREAD

**Issue by unh3x** [s0md3v/XSStrike#57]
Hi, Somdev Sangwan, 
Nice xss detector, but I'm really confused about the relationship between "Levenshtein Algorithm For Accuracy", as I met many false positives recently.
So u mind to explain this confusion ? 
Thx!

**Comment by s0md3v** [comment]
### Methodology Comparison

Other Scanners:
- if `<svg onload=alert()>` is present in response: `vulnerable`
- else: `not vulnerable`

XSStrike:
- if more than 95% part of payload is present in response: `vulnerable`
- if 90-95% part of payload is present in response: `inform user but continue scanning`
- else: `not vulnerable`

#### Why it's useful?
The payload `<svg%0aonload=alert()>` will be reflected in response as follows:
```javascript
<svg
onload=alert()>
```
Notice how `%0a` got changed to a new line. Other scanners won't be able to detect such a case because they will look for `<svg%0aonload=alert()>` and won't find any exact match.
That's why XSStrike does fuzzy matching.
