### ISSUE TITLE
Detailed Logging for crawled information

### ISSUE THREAD

**Issue by fartbagxp** [s0md3v/XSStrike#96]
Hi!

Thank you for the tool. I'm trying to get a easier flow in terms of output for crawled information.
I would like to request this as an enhancement.

I ran the following: 
```
python3 xsstrike.py -u https://www.google.com --crawl

	XSStrike v3.0

[~] Crawling the target
[~] Parsing https://www.google.com
[~] Parsing https://www.google.com/document.getElementById(a.id.substring(1)).href;return!0};(window[
[~] Parsing https://www.google.com/
[~] Parsing https://www.google.com/intl/en/options/
[~] Parsing https://www.google.com/\
[+] Potentially vulnerable objects found at https://www.google.com/
[+] Potentially vulnerable objects found at https://www.google.com
[+] Potentially vulnerable objects found at https://www.google.com/intl/en/options/
[!] Progress: 5/5
```

And I imagine that I would have to go through each of the sublinks to figure out their "potentially vulnerable objects" instead of being able to display all of potential vulnerabilities in one go (even though the application might already have that information).

Is there a better flow in the way this should be operated currently, or will this be an enhancement in the future?

Thank you.

**Comment by s0md3v** [comment]
Hi there,

DOM Scanning isn't very robust in XSStrike and will be improved in future for sure.
It is prone to false positives and prints a lot of lines which ends up cluttering the interface.
However, XSS payloads are printed while crawling because they take just 1 line of space.

![crawling](https://image.ibb.co/iAWNFq/Screenshot-2018-10-27-16-20-36.png)

Thanks for the suggestion.
A switch for printing detailed information will be added real soon.
